version: 2

sources:
  - name: raw_data
    description: "Raw data from CoinGecko API"
    schema: raw_data
    tables:
      - name: cryptocurrency_data
        description: "Raw cryptocurrency market data"
        columns:
          - name: id
            description: "CoinGecko coin ID"
            tests:
              - not_null
          - name: symbol
            description: "Cryptocurrency symbol"
          - name: name
            description: "Cryptocurrency name"
          - name: current_price
            description: "Current price in USD"
            tests:
              - not_null
          - name: market_cap
            description: "Market capitalization in USD"
          - name: market_cap_rank
            description: "Market cap ranking"
          - name: extracted_at
            description: "Timestamp when data was extracted"
            tests:
              - not_null
      
      - name: historical_data
        description: "Historical price and volume data"
        columns:
          - name: coin_id
            description: "CoinGecko coin ID"
            tests:
              - not_null
          - name: timestamp
            description: "Price timestamp"
            tests:
              - not_null
          - name: price
            description: "Historical price in USD"
          - name: volume
            description: "Trading volume"
          - name: market_cap
            description: "Historical market cap"
      
      - name: extraction_log
        description: "Log of data extraction operations"
        columns:
          - name: extraction_type
            description: "Type of extraction performed"
          - name: status
            description: "Success/failure status"
          - name: records_extracted
            description: "Number of records extracted"
